### PR TITLE
Attempt to fix reentrancy bugs

### LINKED ISSUE #485: Thread panicked
I'm getting a weird error when I try to use this profiler as part of a batch submission job. The error logs I'm seeing look like this:

```
=fil-profile= Memory usage will be written out at exit, and stored in profile_200M..
=fil-profile= You can also run the following command while the program is still running to write out peak memory usage up to that point: kill -s SIGUSR2 43523
thread '<unnamed>' panicked at 'already borrowed: BorrowMutError', filpreload/src/lib.rs:138:33
stack backtrace:
```

Then, that's it. The program never starts. The same command on the command line works fine. Here is my input command:

```
fil-profile --no-browser -o profile_200M run -m \
    neat --log-level DEBUG \
        --no-log \
        model-seq-err \
        -o DefaultSingleEndedBinned \
        -i reads/sub200M_read1.fq \
        --overwrite
```

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #485, maybe. Will need @joshfactorial to test the generated wheels to verify.

### CODE REVIEW

**Comment by joshfactorial** [comment]
Sure -- how would I do that?

**Comment by itamarst** [comment]
[Uploading ubuntu-20.04-3.8-wheel.zip…](Wheels built from this branch)

Can you try the version included in the zip file above?

**Comment by joshfactorial** [comment]
I will run it today!

Get BlueMail for Android<https://bluemail.me>
On Mar 15, 2023, at 9:43 AM, Itamar Turner-Trauring ***@***.******@***.***>> wrote:

@joshfactorial<https://urldefense.com/v3/__https://github.com/joshfactorial__;!!DZ3fjg!4tMpIRUPTJY1-381OUsWDdcVoQIL-j3yTtN64csBdZyBtVkC9ly8iPg6gzUrLa1p2b7np5u7Hzl9rq1--3dkVoGashCdsA$> if you have time today, would love to hear if this fixes it.

**Comment by joshfactorial** [comment]
It'll be awhile before I see any final results, but it IS running!

**Comment by joshfactorial** [comment]
I wasn't sure how to approach it so I just started attempting to install the lowest numbered file in the zip. The correct one ended up being `filprofiler-2023.3.1.dev8+g7aa6d0b-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` Maybe those are just for different kernels?

**Comment by itamarst** [comment]
The "manylinux2014" means "this will work on RHEL7 or later", or more accurately, versions of glibc matching RHEL7's or later. "manylinux_2_17" means "glibc 2.17 or later", which is what RHEL7 uses.

**Comment by joshfactorial** [comment]
It worked!

**Comment by itamarst** [comment]
Great, thank you!

**Pull request merged**
