### PR TITLE
Fix for breakage on macOS

### LINKED ISSUE #135: Error writing SVG: I/O error: No stack counts found
## Version information
Fil: 0.15.0
Python: 3.8.6 (default, Oct 26 2020, 20:21:46) 
[Clang 11.0.3 (clang-1103.0.32.62)]

Running on MacOS 11.2.1. Using example.py from https://github.com/pythonspeed/filprofiler/blob/master/tests/test-scripts/example.py. Empty peak-memory.prof file created.

(.venv) ~/Projects/data-sources $ fil-profile run example.py 
=fil-profile= Memory usage will be written out at exit, and opened automatically in a browser.
=fil-profile= You can also run the following command while the program is still running to write out peak memory usage up to that point: kill -s SIGUSR2 71645
DEMO TIME!
DONE! 2.552993059158325
=fil-profile= Preparing to write to fil-result/2021-02-18T22:12:29.759
=fil-profile= Error writing SVG: I/O error: No stack counts found
=fil-profile= Error writing SVG: I/O error: No stack counts found
=fil-profile= Wrote HTML report to fil-result/2021-02-18T22:12:29.759/index.html
0:109: execution error: File some object wasn’t found. (-43)

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #135

### CODE REVIEW

**Comment by itamarst** [comment]
@npalombo can you try the wheels at https://github.com/pythonspeed/filprofiler/actions/runs/581837915 and see if they fix your problem? The Artifacts section at the bottom of the page.

**Comment by itamarst** [comment]
I.e. download, then `pip install path/to/downloaded.whl`.

**Comment by npalombo** [comment]
Getting 404 when trying to download any of those artifacts.

**Comment by itamarst** [comment]
Hm, I guess it's a permissions issue. Try this:

[macos-latest-3.8-wheel.zip](https://github.com/pythonspeed/filprofiler/files/6018724/macos-latest-3.8-wheel.zip)

**Comment by npalombo** [comment]
That works, thanks.

**Comment by itamarst** [comment]
The download works, or the code (i.e. Fil) works?

**Comment by npalombo** [comment]
Both. I was able to download, install and run the profiler.

**Comment by itamarst** [comment]
Excellent. 

Thank you for filing the bug, and for testing the fix, really appreciate it! Please let me know if you have any other questions, ideas, or any other feedback, or in general if there's any other way I can help.

**Pull request merged**
