### PR TITLE
Don't load aligned_alloc on macOS

### LINKED ISSUE #36: Couldn't load aligned_alloc(): dlsym(RTLD_NEXT, aligned_alloc): symbol not found
On Mac OS X, Mojave Version 10.14.6, Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64

running:

fil-profile run test.py

where test.py just prints hello gives the error:

Couldn't load aligned_alloc(): dlsym(RTLD_NEXT, aligned_alloc): symbol not found

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #36.

### CODE REVIEW

**Comment by itamarst** [comment]
@dderick23 if you look in upper right hand of https://github.com/pythonspeed/filprofiler/pull/39/checks?check_run_id=842814179, there's a drop down with artifacts. Could you download the appropriate wheel for Python version you use, and see if it fixes the problem on Mojave?

**Comment by itamarst** [comment]
You can just `pip install ./path/to/thing-you-download.whl`.

**Comment by derrickk23** [comment]
After installing the wheel, fil_profiler works.  Thank you for the fix!

**Comment by itamarst** [comment]
Thank you for testing it!

**Pull request merged**
